// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TvTracker.Data;

#nullable disable

namespace TvTracker.Migrations
{
    [DbContext(typeof(TvTrackerContext))]
    [Migration("20260217155848_modelRefactor")]
    partial class modelRefactor
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("TvTracker.Models.Actor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PosterPath")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Actors", (string)null);
                });

            modelBuilder.Entity("TvTracker.Models.CastMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CharacterName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("CreditIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MediaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ActorId");

                    b.HasIndex("MediaId");

                    b.ToTable("CastMembers", (string)null);
                });

            modelBuilder.Entity("TvTracker.Models.Media", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "MediaInfo", "TvTracker.Models.Media.MediaInfo#MediaMetaInfo", b1 =>
                        {
                            b1.IsRequired();

                            b1.PrimitiveCollection<string>("Genres")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Language")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("TEXT");

                            b1.Property<string>("PosterPath")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT");
                        });

                    b.HasKey("Id");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("TvTracker.Models.Profile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("TvTracker.Models.Season", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EpisodeLength")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Episodes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeasonNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeriesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SeriesId");

                    b.ToTable("Seasons", (string)null);
                });

            modelBuilder.Entity("TvTracker.Models.UserMedia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("WatchedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.ToTable("UserMedia");

                    b.HasDiscriminator<string>("Discriminator").HasValue("UserMedia");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("TvTracker.Models.Movie", b =>
                {
                    b.HasBaseType("TvTracker.Models.Media");

                    b.Property<int>("Length")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("INTEGER");

                    b.ToTable("Movies", (string)null);
                });

            modelBuilder.Entity("TvTracker.Models.Series", b =>
                {
                    b.HasBaseType("TvTracker.Models.Media");

                    b.Property<int>("AirStatus")
                        .HasColumnType("INTEGER");

                    b.ToTable("Series", (string)null);
                });

            modelBuilder.Entity("TvTracker.Models.UserMovie", b =>
                {
                    b.HasBaseType("TvTracker.Models.UserMedia");

                    b.Property<int>("MovieId")
                        .HasColumnType("INTEGER");

                    b.HasIndex("MovieId");

                    b.HasDiscriminator().HasValue("UserMovie");
                });

            modelBuilder.Entity("TvTracker.Models.UserSeason", b =>
                {
                    b.HasBaseType("TvTracker.Models.UserMedia");

                    b.Property<int>("SeasonId")
                        .HasColumnType("INTEGER");

                    b.HasIndex("SeasonId");

                    b.HasDiscriminator().HasValue("UserSeason");
                });

            modelBuilder.Entity("TvTracker.Models.UserSeries", b =>
                {
                    b.HasBaseType("TvTracker.Models.UserMedia");

                    b.Property<int>("SeriesId")
                        .HasColumnType("INTEGER");

                    b.HasIndex("SeriesId");

                    b.HasDiscriminator().HasValue("UserSeries");
                });

            modelBuilder.Entity("TvTracker.Models.CastMember", b =>
                {
                    b.HasOne("TvTracker.Models.Actor", "Actor")
                        .WithMany()
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TvTracker.Models.Media", null)
                        .WithMany("Cast")
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actor");
                });

            modelBuilder.Entity("TvTracker.Models.Season", b =>
                {
                    b.HasOne("TvTracker.Models.Series", null)
                        .WithMany("Seasons")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TvTracker.Models.UserMedia", b =>
                {
                    b.HasOne("TvTracker.Models.Profile", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("TvTracker.Models.UserMovie", b =>
                {
                    b.HasOne("TvTracker.Models.Movie", "Movie")
                        .WithMany()
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("TvTracker.Models.UserSeason", b =>
                {
                    b.HasOne("TvTracker.Models.Season", "Season")
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Season");
                });

            modelBuilder.Entity("TvTracker.Models.UserSeries", b =>
                {
                    b.HasOne("TvTracker.Models.Series", "Series")
                        .WithMany()
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Series");
                });

            modelBuilder.Entity("TvTracker.Models.Media", b =>
                {
                    b.Navigation("Cast");
                });

            modelBuilder.Entity("TvTracker.Models.Series", b =>
                {
                    b.Navigation("Seasons");
                });
#pragma warning restore 612, 618
        }
    }
}
